# Generated by Django 2.2.15 on 2023-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlelogcsv',
            name='data',
            field=models.TextField(),
        ),
    ]
